### ISSUE TITLE
Doesn't work with flutter 3.19.   Update packages.

### ISSUE THREAD

**Issue by sgehrman** [moham96/dtorrent_task#10]
Because every version of flutter from sdk depends on meta 1.11.0 and events_emitter2 >=1.0.3 depends on
  meta >=1.9.0 <=1.10.0, flutter from sdk is incompatible with events_emitter2 >=1.0.3.
And because dtorrent_task >=0.3.3 depends on events_emitter2 ^1.0.3, flutter from sdk is incompatible
  with dtorrent_task >=0.3.3.
So, because deckr depends on both dtorrent_task ^0.3.3 and flutter from sdk, version solving failed.

**Comment by moham96** [comment]
Fixed in https://github.com/moham96/events_emitter2/commit/6e232e704b48b7e6c2bccbc081c0970df2686337 please run `dart pub get`
