### ISSUE TITLE
Only one peer is connected at a time

### ISSUE THREAD

**Issue by tanishbajaj101** [moham96/dtorrent_task#13]
Upon analysing the terminal I realised that all data is only being downloaded from one Peer here it is 66.42.170.16 and it is not being connected to any other

[_TCPPeer] Sending have information to the peer: [0, 0, 0, 0], 227
[_TCPPeer] Received request for Piece (228, 147456) content, downloaded 59473920 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 163840) content, downloaded 59490304 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 180224) content, downloaded 59490304 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 196608) content, downloaded 59523072 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 212992) content, downloaded 59523072 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 229376) content, downloaded 59555840 bytes from the current Peer PeerType.TCP 66.42.170.16:5988
[_TCPPeer] Received request for Piece (228, 245760) content, downloaded 59555840 bytes from the current Peer PeerType.TCP 66.42.170.16:5988

**Comment by moham96** [comment]
Maybe the torrent you're downloading only has one seeder? testing using the big buck bunny torrent i see at least 16-18 peers connected

**Comment by moham96** [comment]
I will close it for lack of response, feel free to reopen it
