### ISSUE TITLE
`reusePort` not supported for Windows.flutter

### ISSUE THREAD

**Issue by BTMuli** [moham96/dtorrent_task#22]
I don't know why it occurs.

```shell
Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.flutter: 
```

**Comment by moham96** [comment]
try with 8c3fb63902c3eae9eb6ae5218742fd6c12cc1a2c

**Comment by BTMuli** [comment]
> try with [8c3fb63](https://github.com/moham96/dtorrent_task/commit/8c3fb63902c3eae9eb6ae5218742fd6c12cc1a2c)

Fine,but https://github.com/moham96/dtorrent_task/issues/17#issuecomment-2086512530

**Comment by moham96** [comment]
> > try with [8c3fb63](https://github.com/moham96/dtorrent_task/commit/8c3fb63902c3eae9eb6ae5218742fd6c12cc1a2c)
> 
> Fine,but [#17 (comment)](https://github.com/moham96/dtorrent_task/issues/17#issuecomment-2086512530)

I did notice this bug sometimes but i don't have reproducible steps unfortunately, sometimes it goes days without this bug appearing

**Comment by BTMuli** [comment]
> If you have reproducible steps, it would be great, i would be able to debug this issue

Idk,it occurs often at hotreload or page refresh,maybe init a task twice could reproduce?

**Comment by BTMuli** [comment]
Since the issues raised in the issue have been resolved, the other issues in the comment also have separate issues, so closed
