### ISSUE TITLE
update pub?  missing exports

### ISSUE THREAD

**Issue by sgehrman** [moham96/dtorrent_task#4]
I have 0.3.3, but it doesn't have:

export 'src/stream/stream.dart';
export 'src/stream/stream_events.dart';
export 'src/task_events.dart';

Do you need to post the latest to pub.dev?

**Comment by moham96** [comment]
yes, been pushing alot of updates to git but not pub.dev, will release new one soon

**Comment by moham96** [comment]
Can you do `pub upgrade` and report back now? i released new versions

**Comment by sgehrman** [comment]
yeah, works, Thanks!
