### ISSUE TITLE
explain this .bt.state file

### ISSUE THREAD

**Issue by sgehrman** [moham96/dtorrent_task#6]
I noticed that if I try to download a file twice, the second time it doesn't work.

I found this state file:  51eb9f733ceb792822d6cfa62b0a033b7b3732b1.bt.state

If I delete that it works.  What is this and do I need to delete it everytime?

**Comment by sgehrman** [comment]
I think I fixed it.
```
      // delete state file first
      final stateFile = await StateFile.getStateFile(downloadsPath, model!);
      await stateFile.delete();

      // start download
      await task.start();
```

**Comment by moham96** [comment]
what do you mean download the file twice? if you need to download it twice then you need to specify a different directory,

the `bt.state` file is used to track progress of the download

**Comment by sgehrman** [comment]
ok, I'm just trying to make it "idiot proof".  If someone downloads a file, then deletes that file, and then downloads it again, it won't download if the bt.state file is still there, so it's a bit confusing.
