### ISSUE TITLE
Large torrents with large number of pieces cause an overflow

### ISSUE THREAD

**Issue by sgehrman** [moham96/dtorrent_task#8]
I tried this torrent and it seemed to churn for hours, but didn't work?  I maybe wrong, but wanted you to test it to confirm.

[Stable diffusion models.zip](https://github.com/moham96/dtorrent_task/files/13370636/Stable.diffusion.models.zip)

**Comment by moham96** [comment]
I was able to re produce, this seems to be happening because the file is very big and has many pieces.
an overhaul might be needed to how we process and generate pieces;

**Comment by moham96** [comment]
mainly caused by 601970889a4a1f7452a728cfc3d41c0a8ba2f18f

**Comment by KabaDH** [comment]
> mainly caused by [6019708](https://github.com/moham96/dtorrent_task/commit/601970889a4a1f7452a728cfc3d41c0a8ba2f18f)

Yes, it seems that 0.3.5 is the last stable version. Torrents freeze in the running state.

**Comment by moham96** [comment]
> > mainly caused by [6019708](https://github.com/moham96/dtorrent_task/commit/601970889a4a1f7452a728cfc3d41c0a8ba2f18f)
> 
> Yes, it seems that 0.3.5 is the last stable version. Torrents freeze in the running state.

only the big torrents should crash due to introduction of piece caching, or have you face freezes otherwise?

**Comment by KabaDH** [comment]
> > > mainly caused by [6019708](https://github.com/moham96/dtorrent_task/commit/601970889a4a1f7452a728cfc3d41c0a8ba2f18f)
> > 
> > 
> > Yes, it seems that 0.3.5 is the last stable version. Torrents freeze in the running state.
> 
> only the big torrents should crash due to introduction of piece caching, or have you face freezes otherwise?

Size does not matter. Look here [test](https://github.com/KabaDH/dtorrent_task/tree/test)
I reverted some changes and no problem (but lost optimization). Btw UTP problem remains (sometimes I get exceptions in the console).

**Comment by moham96** [comment]
you mean with the test branch of your repo you can download the torrent that @sgehrman  linked to?

**Comment by moham96** [comment]
I was able to resolve this issue but i need to test memory consumption, can someone link me to healthy torrents with varying sizes: 10GB, 20GB, 30GB, 35GB?
send them to my email if you can't link them here

**Comment by KabaDH** [comment]
> I was able to resolve this issue but i need to test memory consumption, can someone link me to healthy torrents with varying sizes: 10GB, 20GB, 30GB, 35GB? send them to my email if you can't link them here

I sent you some
